name: Build kmods

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write

    steps:
      - name: Set timezone
        id: timezone
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          date +"%Y-%m-%d %H:%M:%S %Z"
          echo "time=$(date +"%Y-%m-%d %H:%M:%S %Z")" >> "$GITHUB_OUTPUT"

      - name: Display system information
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          lscpu | grep -E '^Architecture|^CPU\(s\):|^Model name'
          uname -sr
          lsb_release -a
          free -h
          df -Th

      - name: Checkout
        uses: actions/checkout@v6

      - name: Build
        uses: apoiston/actions@packages
        with:
          private_key: ${{ secrets.PRIVATE_KEY }}
          public_key: ${{ secrets.PUBLIC_KEY }}
          setup_sdk: ${{ secrets.SETUP_SDK }}
          build_kmods: ${{ secrets.BUILD_KMODS }}
          config_buildinfo: builder/config.buildinfo
          enable_build_kmods: true

      - name: Prepare
        run: |
          date +"%Y-%m-%d %H:%M:%S %Z"
          git clone --depth=1 --quiet --branch packages https://github.com/apoiston/index.git
          sed -i "s/N\/A/$(date +"%Y-%m-%d %H:%M:%S %Z")/g" index/index.html
          rsync -a --quiet --include="*.html" --include="*.css" --include="*.js" --exclude="*" index/ kmods/
          rsync -a --quiet openwrt/builder-kmods/snapshots kmods/
          printf '%s' "${{ secrets.PUBLIC_KEY }}" > kmods/public-key.pem

      - name: Commit
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./kmods
          publish_branch: kmods
          full_commit_message: "build: ${{ steps.timezone.outputs.time }} [KMODS]"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: false
          disable_nojekyll: true
